CONFIG_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_BOOT_BANNER=y

CONFIG_BFLB_ZIGBEE=y
CONFIG_BFLB_SHIM_HEAP_SIZE=16384

CONFIG_HEAP_MEM_POOL_SIZE=4096

CONFIG_CPP=y
CONFIG_MINIMAL_LIBCPP=y

# Disable the Zephyr 802.15.4 driver — zigbee stack owns the radio
CONFIG_IEEE802154_BFLB=n
CONFIG_NET_L2_IEEE802154=n
CONFIG_NETWORKING=n
