# Shell
CONFIG_SHELL=y

# I2C
CONFIG_I2C=y
CONFIG_I2C_SHELL=y

# Sensor
CONFIG_SENSOR=y
CONFIG_SENSOR_SHELL=y
CONFIG_HTU21D=y
CONFIG_MS5637=y
CONFIG_LSM6DSL=y
CONFIG_LSM6DSL_TRIGGER_GLOBAL_THREAD=y

# BLE
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="TE Smart Badge"

# Logging
CONFIG_LOG=y

# Allow runtime re-init of sensors that fail at boot
CONFIG_DEVICE_MUTABLE=y
