/*
 * Copyright (c) 2025 MASSDRIVER EI (massdriver.space)
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_BFLB_CLOCK_COMMON_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_BFLB_CLOCK_COMMON_H_

#ifndef DT_FREQ_M
#define DT_FREQ_M(x) ((x) * 1000000)
#endif

#define BFLB_CLKID_CLK_ROOT    0
#define BFLB_CLKID_CLK_RC32M   1
#define BFLB_CLKID_CLK_CRYSTAL 2
#define BFLB_CLKID_CLK_BCLK    3
#define BFLB_CLKID_CLK_F32K    4
#define BFLB_CLKID_CLK_XTAL32K 5
#define BFLB_CLKID_CLK_RC32K   6
#define BFLB_CLKID_CLK_PRIVATE 7

#define BFLB_FORCE_ROOT_RC32M   32
#define BFLB_FORCE_ROOT_CRYSTAL 33
#define BFLB_FORCE_ROOT_PLL     34

#define BFLB_F32K_FREQUENCY  32768
#define BFLB_RC32M_FREQUENCY (DT_FREQ_M(32))

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_BFLB_CLOCK_COMMON_H_ */
